In [ ]:
import pandas as pd

In [ ]:
dataset = pd.read_csv("/kc_house_data.csv.zip")

In [ ]:
dataset

id             date  ...  sqft_living15  sqft_lot15
0      7129300520  20141013T000000  ...           1340        5650
1      6414100192  20141209T000000  ...           1690        7639
2      5631500400  20150225T000000  ...           2720        8062
3      2487200875  20141209T000000  ...           1360        5000
4      1954400510  20150218T000000  ...           1800        7503
...           ...              ...  ...            ...         ...
21608   263000018  20140521T000000  ...           1530        1509
21609  6600060120  20150223T000000  ...           1830        7200
21610  1523300141  20140623T000000  ...           1020        2007
21611   291310100  20150116T000000  ...           1410        1287
21612  1523300157  20141015T000000  ...           1020        1357

[21613 rows x 21 columns]

In [ ]:
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LinearRegression as lr

In [ ]:
dataset = dataset.drop(columns=['sqft_living','sqft_lot','waterfront','view','condition','grade','sqft_above','sqft_basement','yr_built','yr_renovated','lat','long','sqft_living15','sqft_lot15'])

KeyError: ignored

In [ ]:
dataset

id             date     price  ...  bathrooms  floors  zipcode
0      7129300520  20141013T000000  221900.0  ...       1.00     1.0    98178
1      6414100192  20141209T000000  538000.0  ...       2.25     2.0    98125
2      5631500400  20150225T000000  180000.0  ...       1.00     1.0    98028
3      2487200875  20141209T000000  604000.0  ...       3.00     1.0    98136
4      1954400510  20150218T000000  510000.0  ...       2.00     1.0    98074
...           ...              ...       ...  ...        ...     ...      ...
21608   263000018  20140521T000000  360000.0  ...       2.50     3.0    98103
21609  6600060120  20150223T000000  400000.0  ...       2.50     2.0    98146
21610  1523300141  20140623T000000  402101.0  ...       0.75     2.0    98144
21611   291310100  20150116T000000  400000.0  ...       2.50     2.0    98027
21612  1523300157  20141015T000000  325000.0  ...       0.75     2.0    98144

[21613 rows x 7 columns]

In [ ]:
X = dataset.iloc[:,[0,3,4,5,6]].values

In [ ]:
X

array([[7.12930052e+09, 3.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        9.81780000e+04],
       [6.41410019e+09, 3.00000000e+00, 2.25000000e+00, 2.00000000e+00,
        9.81250000e+04],
       [5.63150040e+09, 2.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        9.80280000e+04],
       ...,
       [1.52330014e+09, 2.00000000e+00, 7.50000000e-01, 2.00000000e+00,
        9.81440000e+04],
       [2.91310100e+08, 3.00000000e+00, 2.50000000e+00, 2.00000000e+00,
        9.80270000e+04],
       [1.52330016e+09, 2.00000000e+00, 7.50000000e-01, 2.00000000e+00,
        9.81440000e+04]])

In [ ]:
Y = dataset.iloc[:,[2]].values

In [ ]:
Y

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]])

In [ ]:
X_train, X_test, Y_train, Y_test = tts(X,Y, test_size=0.4, random_state=0)

In [ ]:
X_train

array([[5.97000550e+08, 4.00000000e+00, 2.50000000e+00, 1.50000000e+00,
        9.81440000e+04],
       [1.68520011e+09, 3.00000000e+00, 1.75000000e+00, 1.00000000e+00,
        9.80920000e+04],
       [6.00350074e+09, 2.00000000e+00, 2.25000000e+00, 3.00000000e+00,
        9.81220000e+04],
       ...,
       [5.46950120e+09, 3.00000000e+00, 2.25000000e+00, 1.00000000e+00,
        9.80420000e+04],
       [3.75160280e+09, 4.00000000e+00, 2.00000000e+00, 2.00000000e+00,
        9.80010000e+04],
       [4.03860026e+09, 4.00000000e+00, 2.25000000e+00, 1.00000000e+00,
        9.80080000e+04]])

In [ ]:
X_test

array([[1.45360231e+09, 2.00000000e+00, 1.50000000e+00, 3.00000000e+00,
        9.81250000e+04],
       [2.22505921e+09, 4.00000000e+00, 3.25000000e+00, 2.00000000e+00,
        9.80050000e+04],
       [2.76800027e+09, 2.00000000e+00, 7.50000000e-01, 1.00000000e+00,
        9.81070000e+04],
       ...,
       [5.31610082e+09, 3.00000000e+00, 3.00000000e+00, 2.00000000e+00,
        9.81120000e+04],
       [7.85213055e+09, 4.00000000e+00, 2.50000000e+00, 2.00000000e+00,
        9.80650000e+04],
       [1.52355048e+09, 3.00000000e+00, 2.50000000e+00, 2.00000000e+00,
        9.80520000e+04]])

In [ ]:
Y_train

array([[350000.],
       [225000.],
       [640000.],
       ...,
       [431000.],
       [411000.],
       [699900.]])

In [ ]:
Y_test

array([[ 297000.],
       [1578000.],
       [ 562100.],
       ...,
       [1195000.],
       [ 530000.],
       [ 580000.]])

In [ ]:
model = lr()

In [ ]:
model

LinearRegression()

In [ ]:
model.fit(X_train, Y_train)

LinearRegression()

In [ ]:
X_train = X_train.reshape(-1,1)
X_test = X_test.reshape(-1,1)

In [ ]:
X_train

array([[5.9700055e+08],
       [4.0000000e+00],
       [2.5000000e+00],
       ...,
       [2.2500000e+00],
       [1.0000000e+00],
       [9.8008000e+04]])

In [ ]:
Y_pred = model.predict(X_test)

ValueError: ignored